### ISSUE TITLE
Set up continious deployment of BOS

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/docs.github.io#13]

**Comment by vandot** [comment]
Repo: https://github.com/ethersphere/publish-bookofswarm/

Manually download new PDF from Overleaf, put it inside pdfs folder inside repo and push
Latest PDF will be uploaded and set to bzz://latest.bookofswarm.eth
Idea was to have archive as well, we will have it inside git repo, at least for now

**Comment by crtahlin** [comment]
Cannot access https://github.com/ethersphere/publish-bookofswarm/ to verify.

I get an 404 error, I guess I might not have permissions. 

Please check. Also, at least @significance and @zelig should also have access (if that is the issue).

**Comment by vandot** [comment]
That was the problem, sorry, I invited you. @significance and @zelig already had access

**Comment by crtahlin** [comment]
@vandot please also give accees to @Eknir and close the issue.

**Comment by vandot** [comment]
@crtahlin done
