### ISSUE TITLE
Set up continious deployment of bee-docs

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/docs.github.io#14]

**Comment by vandot** [comment]
Repo: https://github.com/ethersphere/docs.github.io (renamed exsting bee-documentation repo)

Change docs and push
Latest docs will be pubished in two places:
https://ethersphere.github.io/docs.github.io/ Web2 hosted on Github (for this I needed to rename repo)
https://swarm-gateways.net/bzz:/docs.swarm.eth

**Comment by crtahlin** [comment]
FYI @significance @Eknir .
