### ISSUE TITLE
Ensure persistence of content on web3

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/docs.github.io#48]
Eg. the :
- BOS
- Docs website

Should not disappear. 
Therefore, add pinning into continious deployment. Also, if that not sufficent, include periodic reupload of the content (to keep it from getting garbage collected).

**Comment by crtahlin** [comment]
Also: 
- API reference (API and debug API)

**Comment by crtahlin** [comment]
Set up reupload of content daily. Or ping it every one minute, for example, to keep it from garbage collection. 
@vandot Could an uptime monitoring be set up, that pings some pages and maybe even reuploads it if missing?

Been discussing this with @Eknir and @significance . It would benefit this to be generally available for different projects. Talk to @significance about details.

**Comment by vandot** [comment]
@crtahlin we are downloading sites every 15min using Github Actions and monitoring is set using StatusCake
