### ISSUE TITLE
Add go requirements

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/docs.github.io#56]
What is minimum go version number to build bee?

**Comment by janos** [comment]
We are supporting the latest Go release, any older may work, but we are trying to keep up to date with the latest. Currently it is version 1.4.

**Comment by janos** [comment]
It would be good to add Go version requirement to "Installation from source" section in "Installation". It may differ from one version to another, but currently version 0.1.0 and current master require 1.14. Support for 1.15 is depending on fixing upstream issues in bee dependencies https://github.com/ethersphere/bee/issues/575.
